//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG6212_POE_pt2
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        public int moduleID { get; set; }
        public string moduleCode { get; set; }
        public string moduleName { get; set; }
        public int credits { get; set; }
        public int hrs { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime studyDate { get; set; }
        public int Weeks { get; set; }
        public int studyHrs { get; set; }
        public int remain { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual user user { get; set; }
    }
}
